### ISSUE TITLE
Invalid hex-character pattern in string in file "C:\Users\songlcy\Desktop\splitBundle\node_modules\react-native\Libraries\Blob\Blob.js" at line 19:17

### ISSUE THREAD

**Issue by songxiaoliang** [feixue1232/react-native-split-index#3]
Invalid hex-character pattern in string in file "C:\Users\songlcy\Desktop\splitBundle\node_modules\react-native\Libraries\Blob\Blob.js" at line 19:17

**Comment by feixue1232** [comment]
在windows上报这个错误的原因是：用来作为数据下标作用的字符串，在mac上的路径和windows上的不一致导致。请看我在博客中修改metro-bundler的两个文件的位置，将字符串里“\”替换成别的字符如“_"试下，这样就可以了~ 我这几天暂时不方便更新github，过几天我把这个问题解决文件在github和博客更新下~

**Comment by songxiaoliang** [comment]
@feixue1232 期待很久了，终于等到了回复。方便给个联系方式吗，有些问题要请教。

**Comment by songxiaoliang** [comment]
@feixue1232 我看两个文件中，没有涉及到 “\”呀，修改的地方我看都用 //[w] 标注了，也没发现。能帮我指定下具体位置吗？

**Comment by feixue1232** [comment]
> @feixue1232 期待很久了，终于等到了回复。方便给个联系方式吗，有些问题要请教。
加我WX吧，feixue1232,添加时说明“RN讨论”

**Comment by feixue1232** [comment]
@songxiaoliang 加我WX吧，feixue1232,添加时说明“RN讨论”

**Comment by songxiaoliang** [comment]
@feixue1232 你好，我将 \ 替换成了 _ 或者 / 都不可以，在加载common的bundle时，提示错误：
Requiring unknown module "node_modules/react-native/Libraries/Utilities/defineLazyObjectProperty.js". (common.bundle:2)

**Comment by songxiaoliang** [comment]
@feixue1232 修改的代码如下：
 for (const _ref2 of dependencyPairs) {var _ref3 = _slicedToArray(_ref2, 2);const name = _ref3[0];const path = _ref3[1];
  
      resolvedDeps[name] = "'" + this.getModuleForPath(path).localPath.replace(/\\/g, '/') + "'";   
    
      // resolvedDeps[name] = getModuleId({ path });  // [wk] 源文件
    }

**Comment by feixue1232** [comment]
源码已修复此问题
